using DevExpress.XtraBars;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.Entity;
using Models;

namespace Win.Ownr
{
    public partial class frmOwners : DevExpress.XtraBars.FluentDesignSystem.FluentDesignForm
    {
        public frmOwners()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            // This line of code is generated by Data Source Configuration Wizard
            entityServerModeSource1.QueryableSource = new Models.ModelDb().Owners;
        }

        private void frmOwners_Load(object sender, EventArgs e)
        {

        }

        private void accordionControlElement3_Click(object sender, EventArgs e)
        {
            if (gridView1.GetFocusedRow() is Owners item)
            {
                frmAddEditOwner frm = new frmAddEditOwner(item.Id, MethodType.Edit);
                frm.ShowDialog();
            }
            entityServerModeSource1.QueryableSource = new Models.ModelDb().Owners;
            gridView1.RefreshData();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            frmAddEditOwner frm = new frmAddEditOwner(methodType: MethodType.Add);
            frm.ShowDialog();
            entityServerModeSource1.Reload();
        }
    }
}
