using DevExpress.XtraBars;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using DevExpress.XtraGrid.Views.Grid;
using Models;
using Models.Repository;

namespace Win.Pt
{
    public partial class frmPatients : DevExpress.XtraBars.FluentDesignSystem.FluentDesignForm
    {
        private Patients Patient;

        public frmPatients()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            this.PatientBindingSource.DataSource = new UnitOfWork().PatientsRepo.Get();

        }

      

        private void btnAddPatient_Click(object sender, EventArgs e)
        {
            frmAddEditPatient frm = new frmAddEditPatient(null, MethodType.Add);
            frm.ShowDialog();
            this.PatientBindingSource.DataSource = new UnitOfWork().PatientsRepo.Get();
        }

        private void accordionControlElement3_Click(object sender, EventArgs e)
        {
            var patient = PatientGrid.GetFocusedRow() as Patients;
            if (patient == null)
                return;
            frmAddEditPatient frm = new frmAddEditPatient(patient.Id, MethodType.Edit);
            frm.ShowDialog();
            this.PatientBindingSource.DataSource = new UnitOfWork().PatientsRepo.Get();

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void PatientGrid_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
           // this.Patient = (sender as GridView)?.GetFocusedRow() as Patients;
        }

        private void frmPatients_Load(object sender, EventArgs e)
        {

        }
    }
}
