using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using Models;

namespace Win.cnfnmnt
{
    public partial class ucConfinedmentDetails : DevExpress.XtraEditors.XtraUserControl
    {
      
        public ucConfinedmentDetails()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            entityServerModeSource1.QueryableSource = new Models.ModelDb().Owners;
        }

        private void gridLookUpEdit1_EditValueChanged(object sender, EventArgs e)
        {
            if (gridLookUpEdit1.GetSelectedDataRow() is Owners owners)
            {
                txtAddress.EditValue = owners?.Address;
                txtTelNo.EditValue = owners?.TelNo;
            }
        }
    }
}
