using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;

namespace Win.cnfnmnt
{
    public partial class ucConfinementGrid : DevExpress.XtraEditors.XtraUserControl
    {
        public GridView ConfinedmentGrid => gridView1;
        public ucConfinementGrid()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            entityServerModeSource1.QueryableSource = new Models.ModelDb().ConfinementRecords;
        }

        private void txtSearch_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                var search = txtSearch.Text;
                entityServerModeSource1.QueryableSource =
                new Models.ModelDb().ConfinementRecords.Where(m => m.Observations.Contains(search));
            }
        }

        public void Reload()
        {
            entityServerModeSource1.QueryableSource = new Models.ModelDb().ConfinementRecords;
        }
    }
}
