using DevExpress.XtraBars;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using Models;

namespace Win.vt
{
    public partial class frmVeterinary : DevExpress.XtraBars.FluentDesignSystem.FluentDesignForm
    {
        public frmVeterinary()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            entityServerModeSource1.QueryableSource = new Models.ModelDb().Veterinaries;
        }

        private void frmVeterinary_Load(object sender, EventArgs e)
        {

        }

        private void accordionControlElement4_Click(object sender, EventArgs e)
        {
            frmAddEditVeterinary frm = new frmAddEditVeterinary(null, Models.MethodType.Add);
            frm.ShowDialog();
            entityServerModeSource1.QueryableSource = new Models.ModelDb().Veterinaries;
        }

        private void accordionControlElement5_Click(object sender, EventArgs e)
        {

            if (gridView1.GetFocusedRow() is Veterinaries item)
            {
                frmAddEditVeterinary frm = new frmAddEditVeterinary(item.Id, Models.MethodType.Edit);
                frm.ShowDialog();
                entityServerModeSource1.QueryableSource = new Models.ModelDb().Veterinaries;
            }

        }
    }
}
