//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barangays
    {
        public int Id { get; set; }
        public string Barangay { get; set; }
        public Nullable<int> TownId { get; set; }
    
        public virtual Towns1 Towns1 { get; set; }
    }
}
