//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfinementRecords
    {
        public int Id { get; set; }
        public Nullable<int> VetId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string Observations { get; set; }
        public string Status { get; set; }
        public string Medication { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Owners Owners { get; set; }
        public virtual Patients Patients { get; set; }
        public virtual Veterinaries Veterinaries { get; set; }
    }
}
